# Generated by Django 3.1.12 on 2022-05-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circuitos',
        ),
    ]
