# Generated by Django 3.2.12 on 2022-04-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circuitos',
            new_name='Circuito',
        ),
    ]
