# Generated by Django 3.2.12 on 2022-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=70)),
                ('content', models.TextField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FormulaOne',
        ),
    ]
