# Generated by Django 3.2.12 on 2022-04-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaOne', '0002_auto_20220413_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Comparacion',
        ),
    ]
